version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # --> /.github/workflows/
    schedule:
      interval: "daily"
      time: "05:00"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    assignees:
      - "nclsbayona"
    commit-message:
      prefix: "pip update"
      include: "scope"
