name: "README Build"
author: "nclsbayona"
description: "Update your README file with some data acquired via some APIs and information about you"

inputs:
  python-version:
    required: false
    description: 'Python version to use to run the file'
    default: '3.10'
  wakatime-api-key:
    required: false
    description: 'Wakatime API Key to display information about time online'
  nasa-api-key:
    required: false
    description: 'Nasa API Key to display a photo of the universe'
  username:
    required: true
    description: 'Username of the user running the action'
  # github-token:
    # required: true
    # description: 'GitHub Token with permissions to push the new README to the repository'

# outputs:
  # status:
    # description: 'The status of the action run'
    
runs:
  using: "composite"
  steps: 
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }} 
    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt
    - name: Generate README
      shell: bash
      run: python main.py
      env:
        WAKATIME_API_KEY: ${{ inputs.wakatime-api-key }}
        NASA_KEY: ${{ inputs.nasa-api-key }}
        USERNAME: ${{ inputs.username }}
  
branding:
  icon: user-check
  color: blue
