# This is a basic workflow to help you get started with Actions
name: CI
on: [pull_request]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
